#!/bin/bash

echo 'Cleaning...'
if [ ! -d out/ ]; then
  mkdir out
fi
echo 'Compiling...'
CPLUS_INCLUDE_PATH=`pwd`/src make &&
echo 'Compile successfully. Use `cd out && ./minisql` to run this program.'
